# SPDX-License-Identifier: Apache-2.0
"""
Tests for vllm_mlx/server.py utility functions.

Generated by MiniMax-M2.5 via openclaw simulation, reviewed and fixed by Claude.
"""

from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from vllm_mlx.api.models import FunctionCall, ToolCall
from vllm_mlx.engine.base import GenerationOutput

# ---------------------------------------------------------------------------
# _resolve_temperature / _resolve_top_p
# ---------------------------------------------------------------------------


class TestResolveTemperature:
    """Tests for _resolve_temperature function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.3) == 0.3
        finally:
            cfg.default_temperature = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(None) == 0.8
        finally:
            cfg.default_temperature = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = None
            assert server._resolve_temperature(None) == server._FALLBACK_TEMPERATURE
        finally:
            cfg.default_temperature = old

    def test_zero_is_valid_request_value(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.0) == 0.0
        finally:
            cfg.default_temperature = old


class TestResolveTopP:
    """Tests for _resolve_top_p function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(0.7) == 0.7
        finally:
            cfg.default_top_p = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(None) == 0.95
        finally:
            cfg.default_top_p = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = None
            assert server._resolve_top_p(None) == server._FALLBACK_TOP_P
        finally:
            cfg.default_top_p = old


class TestResolveTopK:
    """Tests for _resolve_top_k function.

    Unlike temperature/top_p, top_k has no application-level fallback:
    when both the request and CLI default are unset, the helper returns
    None so the caller skips forwarding and the engine's own
    SamplingParams default applies.
    """

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(50) == 50
        finally:
            cfg.default_top_k = old

    def test_cli_default_used_when_request_none(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(None) == 20
        finally:
            cfg.default_top_k = old

    def test_returns_none_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = None
            assert server._resolve_top_k(None) is None
        finally:
            cfg.default_top_k = old

    def test_zero_request_value_is_forwarded(self):
        """top_k=0 is a valid disable-top-k signal in some samplers."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(0) == 0
        finally:
            cfg.default_top_k = old


# ---------------------------------------------------------------------------
# Resolve cascade: alias overlay + generation_config overlay
# ---------------------------------------------------------------------------


class TestResolveCascade:
    """Verify the 4-layer resolve chain:

        request  >  CLI default  >  alias overlay  >  generation_config

    Documented in service/helpers.py::_cascade. We exercise it through
    the public resolve_* helpers because that's the contract route
    handlers actually consume.
    """

    @pytest.fixture(autouse=True)
    def _isolate_config(self):
        """Snapshot/restore the global ServerConfig so cases don't leak."""
        from vllm_mlx.config import get_config

        cfg = get_config()
        snap = {
            "default_temperature": cfg.default_temperature,
            "default_top_p": cfg.default_top_p,
            "default_top_k": cfg.default_top_k,
            "default_min_p": cfg.default_min_p,
            "default_repetition_penalty": cfg.default_repetition_penalty,
            "default_presence_penalty": cfg.default_presence_penalty,
            "default_frequency_penalty": cfg.default_frequency_penalty,
            "alias_recommended_sampling": cfg.alias_recommended_sampling,
            "generation_config_sampling": cfg.generation_config_sampling,
        }
        for k in snap:
            setattr(cfg, k, None)
        yield
        for k, v in snap.items():
            setattr(cfg, k, v)

    def test_temperature_alias_overrides_generation_config(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(None) == 0.5

    def test_temperature_generation_config_used_when_alias_missing(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"temperature": 0.6}
        assert server._resolve_temperature(None) == 0.6

    def test_temperature_cli_default_overrides_overlays(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.default_temperature = 0.9
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(None) == 0.9

    def test_temperature_request_overrides_everything(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.default_temperature = 0.9
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(0.1) == 0.1

    def test_top_p_cascade(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"top_p": 0.95}
        assert server._resolve_top_p(None) == 0.95
        cfg.alias_recommended_sampling = {"top_p": 0.8}
        assert server._resolve_top_p(None) == 0.8

    def test_top_k_int_coercion_through_overlay(self):
        """top_k from JSON arrives as int; cascade must preserve type."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"top_k": 20}
        assert server._resolve_top_k(None) == 20
        assert isinstance(server._resolve_top_k(None), int)

    def test_min_p_cascade(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        # Layer 4 only
        cfg.generation_config_sampling = {"min_p": 0.05}
        assert server._resolve_min_p(None) == 0.05
        # Layer 3 wins
        cfg.alias_recommended_sampling = {"min_p": 0.1}
        assert server._resolve_min_p(None) == 0.1
        # Layer 2 wins
        cfg.default_min_p = 0.2
        assert server._resolve_min_p(None) == 0.2
        # Layer 1 wins
        assert server._resolve_min_p(0.3) == 0.3

    def test_repetition_penalty_returns_none_when_nothing_set(self):
        from vllm_mlx import server

        assert server._resolve_repetition_penalty(None) is None

    def test_repetition_penalty_alias_layer(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"repetition_penalty": 1.1}
        assert server._resolve_repetition_penalty(None) == 1.1

    def test_presence_penalty_request_layer(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"presence_penalty": 0.5}
        # request value wins even when negative
        assert server._resolve_presence_penalty(-0.2) == -0.2

    def test_frequency_penalty_no_signal_returns_none(self):
        from vllm_mlx import server

        assert server._resolve_frequency_penalty(None) is None

    def test_overlay_dict_can_be_empty(self):
        """Empty overlay dicts must be treated as "no value at this layer"."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {}
        cfg.generation_config_sampling = {}
        assert server._resolve_top_k(None) is None
        assert server._resolve_min_p(None) is None

    def test_zero_request_value_is_forwarded(self):
        """0 is a valid request signal for min_p/penalties — must not be
        confused with "unset" by the cascade."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"min_p": 0.1}
        assert server._resolve_min_p(0.0) == 0.0

    def test_zero_request_temperature_wins_over_overlays(self):
        """``temperature=0.0`` from the request must win over alias /
        generation_config overlays — deterministic decoding is a real use."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"temperature": 0.6}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(0.0) == 0.0

    def test_zero_request_top_p_wins_over_overlays(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"top_p": 0.95}
        assert server._resolve_top_p(0.0) == 0.0

    def test_temperature_fallback_when_overlays_empty(self):
        """Empty (non-None) overlay dicts must still hit the hard fallback."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {}
        cfg.generation_config_sampling = {}
        assert server._resolve_temperature(None) == server._FALLBACK_TEMPERATURE
        assert server._resolve_top_p(None) == server._FALLBACK_TOP_P

    def test_top_k_via_alias_overlay(self):
        """Coverage for the alias-layer path (sibling of gen-config test)."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"top_k": 64}
        assert server._resolve_top_k(None) == 64
        assert isinstance(server._resolve_top_k(None), int)

    def test_top_k_float_in_alias_coerced_to_int(self):
        """AliasProfile stores everything as float; resolver must cast back."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"top_k": 20.0}
        result = server._resolve_top_k(None)
        assert result == 20
        assert isinstance(result, int)


# ---------------------------------------------------------------------------
# get_usage
# ---------------------------------------------------------------------------


class TestGetUsage:
    """Tests for get_usage function."""

    def test_full_attributes(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(
            text="hello",
            tokens=[1, 2],
            prompt_tokens=100,
            completion_tokens=50,
        )
        usage = get_usage(output)
        assert usage.prompt_tokens == 100
        assert usage.completion_tokens == 50
        assert usage.total_tokens == 150

    def test_default_values(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="hello")
        usage = get_usage(output)
        assert usage.prompt_tokens == 0
        assert usage.completion_tokens == 0
        assert usage.total_tokens == 0

    def test_only_prompt_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", prompt_tokens=200)
        usage = get_usage(output)
        assert usage.prompt_tokens == 200
        assert usage.total_tokens == 200

    def test_only_completion_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", completion_tokens=75)
        usage = get_usage(output)
        assert usage.completion_tokens == 75
        assert usage.total_tokens == 75


class TestBuildUsageReasoningBreakdown:
    """Pin the ``_build_usage`` reasoning-token allocation contract.

    Per OpenAI spec, ``completion_tokens_details.reasoning_tokens`` is
    a SUBSET of ``completion_tokens`` — derived ``content_tokens =
    completion_tokens - reasoning_tokens`` must be ``>= 0`` and must be
    ``> 0`` whenever ``output.text`` is non-empty. The earlier
    implementation clamped ``reasoning_tokens`` to ``total_completion``
    when ``len(reasoning_text)//4`` exceeded the budget, silently
    attributing ALL completion tokens to reasoning even when the
    assistant emitted content. Surfaced by the v0.6.66 hybrid
    onboarding sweep on ``qwen3.6-27b-8bit`` (300/300 reasoning split
    with non-empty content).
    """

    def _setup_cfg(self, monkeypatch):
        from vllm_mlx.config import get_config

        cfg = get_config()
        # Cache & restore — any non-None string triggers the reasoning
        # breakdown branch in _build_usage.
        old = cfg.reasoning_parser_name
        cfg.reasoning_parser_name = "harmony"
        monkeypatch.setattr(cfg, "reasoning_parser_name", "harmony", raising=False)

        def _restore():
            cfg.reasoning_parser_name = old

        monkeypatch.setattr(cfg, "reasoning_parser_name", "harmony", raising=False)
        return cfg

    def test_long_reasoning_plus_content_leaves_room_for_content(self, monkeypatch):
        """The specific case from the v0.6.66 hybrid onboarding bug
        report: ``len(reasoning_text)//4 > total_completion``, but
        ``output.text`` is non-empty. Derived content_tokens MUST be > 0.
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)
        output = GenerationOutput(
            text="I do not have access to real-time data.",
            completion_tokens=300,
            prompt_tokens=50,
        )
        reasoning_text = "a" * 1300  # > 300 by chars//4

        usage = _build_usage(output, reasoning_text)
        assert usage.completion_tokens == 300
        details = usage.completion_tokens_details
        assert details is not None
        reasoning_tokens = details.reasoning_tokens
        content_tokens = usage.completion_tokens - reasoning_tokens
        assert reasoning_tokens < usage.completion_tokens, (
            f"reasoning_tokens ({reasoning_tokens}) must be < "
            f"completion_tokens ({usage.completion_tokens}) when content "
            f"is non-empty — previously clamped to equal."
        )
        assert content_tokens > 0, (
            f"derived content_tokens must be > 0 when output.text is "
            f"non-empty. got reasoning={reasoning_tokens} of "
            f"{usage.completion_tokens}"
        )

    def test_reasoning_only_empty_content_attributes_all_to_reasoning(
        self, monkeypatch
    ):
        """When ``output.text`` is empty, all completion tokens ARE
        reasoning — the spec invariant ``content_tokens >= 0`` reduces
        to ``content_tokens == 0`` and reasoning_tokens == total.
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)
        output = GenerationOutput(text="", completion_tokens=200, prompt_tokens=50)
        usage = _build_usage(output, "a" * 800)
        assert usage.completion_tokens_details.reasoning_tokens == 200

    def test_balanced_split_proportional(self, monkeypatch):
        """Roughly equal reasoning/content char counts should split the
        completion-token budget roughly 50/50.
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)
        output = GenerationOutput(
            text="abc" * 100, completion_tokens=200, prompt_tokens=50
        )
        usage = _build_usage(output, "def" * 100)
        rt = usage.completion_tokens_details.reasoning_tokens
        # Allow a few tokens of rounding wiggle.
        assert 95 < rt < 105, f"50/50 split should give ~100 reasoning, got {rt}"

    def test_tiny_reasoning_large_content_at_least_one_reasoning_token(
        self, monkeypatch
    ):
        """A single reasoning word with a large content body should
        still report ``reasoning_tokens >= 1`` (the field reflects that
        reasoning happened) AND ``< completion_tokens`` (content must
        retain at least one token).
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)
        output = GenerationOutput(
            text="x" * 1000, completion_tokens=300, prompt_tokens=50
        )
        usage = _build_usage(output, "reason")
        rt = usage.completion_tokens_details.reasoning_tokens
        assert rt >= 1, (
            f"reasoning_tokens must be >= 1 when reasoning happened, got {rt}"
        )
        assert rt < usage.completion_tokens, (
            f"reasoning_tokens ({rt}) must leave room for content "
            f"(completion_tokens={usage.completion_tokens})"
        )

    def test_no_reasoning_no_details(self, monkeypatch):
        """When ``reasoning_text`` is empty, ``completion_tokens_details``
        is None — no spurious zero-reasoning field on responses from
        non-reasoning models.
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)
        output = GenerationOutput(
            text="hello world", completion_tokens=10, prompt_tokens=5
        )
        usage = _build_usage(output, "")
        assert usage.completion_tokens_details is None

    def test_streaming_usage_output_namespace_does_not_crash(self, monkeypatch):
        """The streaming path in ``routes/chat.py`` synthesizes a
        ``_UsageOutput`` ad-hoc namespace with only ``prompt_tokens`` and
        ``completion_tokens`` (plus ``text`` since the content-aware
        split fix). ``_build_usage`` must not ``AttributeError`` if
        ``text`` is ever missing — pr_validate caught this on PR #453
        when pydantic_ai streaming raised ``'_UsageOutput' object has
        no attribute 'text'``. Defensive ``getattr`` in ``_build_usage``
        keeps the route from 500-ing on any future synthetic-output
        shape.
        """
        from vllm_mlx.service.helpers import _build_usage

        self._setup_cfg(monkeypatch)

        # Mimic the streaming-path namespace pre-fix (no ``.text``).
        class _StreamUsage:
            pass

        out = _StreamUsage()
        out.prompt_tokens = 50
        out.completion_tokens = 100

        # Must not raise.
        usage = _build_usage(out, "some reasoning text here")
        assert usage.completion_tokens == 100
        # Without content_chars, fall back to "all tokens are reasoning"
        # for this one synthetic-output path.
        assert usage.completion_tokens_details.reasoning_tokens == 100

        # Now with the ``.text`` attribute populated (post-fix shape).
        out.text = "and here is the actual content body"
        usage = _build_usage(out, "some reasoning text here")
        rt = usage.completion_tokens_details.reasoning_tokens
        assert rt < usage.completion_tokens, (
            f"streaming usage with .text populated must leave room for "
            f"content; got reasoning={rt} of {usage.completion_tokens}"
        )


# ---------------------------------------------------------------------------
# _inject_json_instruction
# ---------------------------------------------------------------------------


class TestInjectJsonInstruction:
    """Tests for _inject_json_instruction function."""

    def test_prepend_to_existing_system_dict(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [
            {"role": "system", "content": "You are helpful."},
            {"role": "user", "content": "Hello"},
        ]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert result[0]["content"].startswith("Respond in JSON.\n\n")
        assert "You are helpful." in result[0]["content"]
        assert len(result) == 2

    def test_prepend_to_existing_system_object(self):
        from vllm_mlx.server import _inject_json_instruction

        class Msg:
            def __init__(self, role, content):
                self.role = role
                self.content = content

        messages = [Msg("system", "You are helpful."), Msg("user", "Hi")]
        result = _inject_json_instruction(messages, "JSON only.")

        assert result[0].content.startswith("JSON only.\n\n")
        assert "You are helpful." in result[0].content

    def test_create_system_when_missing(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hello"}]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert len(result) == 2
        assert result[0]["role"] == "system"
        assert result[0]["content"] == "Respond in JSON."

    def test_empty_messages(self):
        from vllm_mlx.server import _inject_json_instruction

        result = _inject_json_instruction([], "JSON.")
        assert len(result) == 1
        assert result[0]["content"] == "JSON."

    def test_does_not_mutate_list_length(self):
        """Original list should not gain/lose elements."""
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hi"}]
        result = _inject_json_instruction(messages, "JSON.")
        assert len(messages) == 1  # original unchanged
        assert len(result) == 2  # result has new system msg


# ---------------------------------------------------------------------------
# _extract_token_logprob
# ---------------------------------------------------------------------------


class TestExtractTokenLogprob:
    """Tests for _extract_token_logprob function."""

    def _make_logprobs(self, vocab_size=100, token_logprobs=None):
        """Create a mock mx.array with specific token logprobs."""
        arr = np.full(vocab_size, -10.0)  # low default
        if token_logprobs:
            for tid, lp in token_logprobs.items():
                arr[tid] = lp
        mock = MagicMock()
        mock.astype.return_value = mock
        return mock, arr

    def test_basic_top_k(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1, 10: -0.5, 20: -1.0})
        tok = MagicMock()
        tok.decode.side_effect = lambda ids: f"t{ids[0]}"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=3)

        assert result.token == "t5"
        assert result.logprob == pytest.approx(-0.1)
        assert len(result.top_logprobs) == 3
        # Sorted descending
        lps = [t.logprob for t in result.top_logprobs]
        assert lps == sorted(lps, reverse=True)

    def test_top_k_capped_at_vocab(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=100)
        assert len(result.top_logprobs) == 10

    def test_out_of_bounds_token_id(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=500, tokenizer=tok, top_k=3)
        assert result.logprob == 0.0

    def test_bytes_field_populated(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1})
        tok = MagicMock()
        tok.decode.return_value = "hello"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=1)
        assert result.bytes == list(b"hello")

    def test_astype_called_for_conversion(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=1)
        mock.astype.assert_called_once()


# ---------------------------------------------------------------------------
# _extract_streaming_token_logprobs (regression for #220)
# ---------------------------------------------------------------------------


class TestExtractStreamingTokenLogprobs:
    """Regression for #220 — under stream_interval > 1 a single chunk
    carries a list[mx.array] of merged per-step distributions, one per
    token in the merged window. The downstream SSE consumer must see
    one TokenLogProb entry per generated token, not one per flush.

    Pre-#220, the chat-route handler passed the entire list to
    ``_extract_token_logprob`` as one flattened array, producing
    misaligned top-k indices and a single under-counted entry.
    """

    def _make_chunk(self, logprobs, new_text="hi", new_token_ids=None, tokens=None):
        from types import SimpleNamespace

        return SimpleNamespace(
            logprobs=logprobs,
            new_text=new_text,
            new_token_ids=new_token_ids,
            tokens=tokens or [],
        )

    def _make_logprob_array(self, vocab_size=64):
        arr = np.full(vocab_size, -10.0)
        arr[0] = -0.1
        mock = MagicMock()
        mock.astype.return_value = mock
        return mock, arr

    def test_single_array_yields_one_entry(self):
        """Backward-compat — stream_interval=1 still gives one entry."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock, arr = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"
        chunk = self._make_chunk(logprobs=mock, new_token_ids=[7], tokens=[7])

        with patch("numpy.array", return_value=arr):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 1

    def test_list_of_three_yields_three_entries(self):
        """The bug — under stream_interval=4, a 3-token flush carries a
        3-element list and must produce 3 separate TokenLogProb entries.
        """
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock_a, arr_a = self._make_logprob_array()
        mock_b, arr_b = self._make_logprob_array()
        mock_c, arr_c = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"
        chunk = self._make_chunk(
            logprobs=[mock_a, mock_b, mock_c],
            new_token_ids=[10, 11, 12],
            tokens=[10, 11, 12],
        )

        with patch("numpy.array", side_effect=[arr_a, arr_b, arr_c]):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 3, (
            "Expected one TokenLogProb per merged step; pre-fix this "
            "returned a single entry per flush"
        )

    def test_list_pairs_with_new_token_ids(self):
        """Each per-step distribution must be paired with the matching
        ``new_token_ids[i]``, not always the last token in ``tokens``."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock_a, arr_a = self._make_logprob_array()
        mock_b, arr_b = self._make_logprob_array()
        mock_a.astype.return_value = mock_a
        mock_b.astype.return_value = mock_b

        observed_token_ids = []
        tok = MagicMock()

        def fake_decode(ids):
            observed_token_ids.append(ids[0])
            return f"t{ids[0]}"

        tok.decode.side_effect = fake_decode

        chunk = self._make_chunk(
            logprobs=[mock_a, mock_b],
            new_token_ids=[20, 21],
            tokens=[10, 11, 20, 21],
        )

        with patch("numpy.array", side_effect=[arr_a, arr_b]):
            _extract_streaming_token_logprobs(chunk, tok, top_k=1)

        # The sampled token decoded for each entry must come from
        # new_token_ids, not from chunk.tokens[-1] (= 21 for both).
        sampled = [tid for tid in observed_token_ids if tid in (20, 21)]
        assert sampled == [20, 21], (
            f"Per-step token IDs must come from new_token_ids; got {sampled}"
        )

    def test_empty_chunk_returns_empty(self):
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        chunk = self._make_chunk(logprobs=None)
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []

    def test_no_new_text_returns_empty(self):
        """A chunk without new_text (e.g. empty tool-call passthrough)
        produces no logprobs entries even if logprobs is set."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock, _ = self._make_logprob_array()
        chunk = self._make_chunk(logprobs=mock, new_text="")
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []

    def test_empty_list_returns_empty(self):
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        chunk = self._make_chunk(logprobs=[], new_text="hi", new_token_ids=[])
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []

    def test_logprobs_works_with_real_generation_output(self):
        """Pre-fix bug: ``_extract_streaming_token_logprobs`` reached for
        ``chunk.new_token_ids`` but that attribute exists on the engine's
        internal ``RequestOutput`` — NOT on the public ``GenerationOutput``
        dataclass the route actually receives. Every ``logprobs=true``
        request returned HTTP 500 with
        ``AttributeError: 'GenerationOutput' object has no attribute 'new_token_ids'``.

        The earlier ``SimpleNamespace``-based tests in this class masked
        the bug — they fabricated ``new_token_ids`` on the chunk stub.
        This test uses the REAL dataclass so a future change can't
        re-introduce the AttributeError without breaking pinning.

        Surfaced on 2026-05-23 fresh-PyPI v0.6.65 onboarding sweep
        against ``unsloth/Qwen3.6-27B-MLX-8bit``.
        """
        from vllm_mlx.engine.base import GenerationOutput
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        assert not hasattr(GenerationOutput, "new_token_ids"), (
            "If new_token_ids was added to GenerationOutput, update this "
            "test to also verify it's actually populated downstream — "
            "the helper still needs the chunk.tokens fallback for any "
            "engine path that forgets to populate the new field."
        )

        mock, arr = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"

        chunk = GenerationOutput(
            text="hi",
            new_text="hi",
            tokens=[7],
            logprobs=mock,
        )

        with patch("numpy.array", return_value=arr):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 1, (
            f"GenerationOutput chunk with one delta token must yield "
            f"exactly one TokenLogProb entry; got {len(result)}. "
            "Pre-fix this raised AttributeError → 500."
        )

    def test_logprobs_multi_token_real_generation_output(self):
        """Multi-token delta on real ``GenerationOutput``: when an
        upstream flush carries 3 tokens (``stream_interval > 1``), all 3
        per-step logprob distributions must produce 3 TokenLogProb
        entries. Pre-fix this also crashed via the missing attribute;
        post-fix the ``chunk.tokens`` fallback supplies the per-step
        token list correctly.
        """
        from vllm_mlx.engine.base import GenerationOutput
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock_a, arr_a = self._make_logprob_array()
        mock_b, arr_b = self._make_logprob_array()
        mock_c, arr_c = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"

        chunk = GenerationOutput(
            text="abc",
            new_text="abc",
            tokens=[10, 11, 12],
            logprobs=[mock_a, mock_b, mock_c],
        )

        with patch("numpy.array", side_effect=[arr_a, arr_b, arr_c]):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 3, (
            f"3-token delta must yield 3 TokenLogProb entries; got {len(result)}"
        )


# ---------------------------------------------------------------------------
# _validate_tool_call_params
# ---------------------------------------------------------------------------


class TestValidateToolCallParams:
    """Tests for _validate_tool_call_params function."""

    def _make_tools(self, name="get_weather", properties=None):
        if properties is None:
            properties = {"location": {"type": "string"}}
        return [
            {
                "type": "function",
                "function": {
                    "name": name,
                    "parameters": {
                        "type": "object",
                        "properties": properties,
                    },
                },
            }
        ]

    def _make_tool_calls(self, name="get_weather", arguments='{"location": "NYC"}'):
        return [
            ToolCall(
                id="call_1",
                type="function",
                function=FunctionCall(name=name, arguments=arguments),
            )
        ]

    def test_valid_args_no_error(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(),
            self._make_tools(),
        )

    def test_invalid_json_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments="not json {"),
            self._make_tools(),
        )

    def test_type_mismatch_raises_400(self):
        """F-141: type violation now enforced as HTTPException(400)."""
        from fastapi import HTTPException

        from vllm_mlx.server import _validate_tool_call_params

        with pytest.raises(HTTPException) as exc_info:
            _validate_tool_call_params(
                self._make_tool_calls(arguments='{"location": 123}'),
                self._make_tools(properties={"location": {"type": "string"}}),
            )
        assert exc_info.value.status_code == 400
        assert "location" in exc_info.value.detail

    def test_enum_violation_raises_400(self):
        """F-141: enum violation now enforced as HTTPException(400)."""
        from fastapi import HTTPException

        from vllm_mlx.server import _validate_tool_call_params

        with pytest.raises(HTTPException) as exc_info:
            _validate_tool_call_params(
                self._make_tool_calls(arguments='{"unit": "kelvin"}'),
                self._make_tools(
                    properties={
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    }
                ),
            )
        assert exc_info.value.status_code == 400
        assert "unit" in exc_info.value.detail
        assert "kelvin" in exc_info.value.detail or "enum" in exc_info.value.detail

    def test_empty_tool_calls(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params([], self._make_tools())

    def test_pydantic_model_tools(self):
        """Test with Pydantic model tools (have model_dump)."""
        from pydantic import BaseModel

        from vllm_mlx.server import _validate_tool_call_params

        class ToolDef(BaseModel):
            type: str = "function"
            function: dict

        tools = [
            ToolDef(
                function={
                    "name": "get_weather",
                    "parameters": {
                        "type": "object",
                        "properties": {"location": {"type": "string"}},
                    },
                }
            )
        ]
        _validate_tool_call_params(
            self._make_tool_calls(),
            tools,
        )


# ---------------------------------------------------------------------------
# extract_json_from_response guard tests
# ---------------------------------------------------------------------------


class TestExtractJsonFromResponse:
    """Tests for extract_json_from_response showing why guard is needed."""

    def test_extracts_json_from_reasoning_text(self):
        """Correctly extracts JSON from reasoning prefix."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = 'Let me think... {"result": 42}'
        assert extract_json_from_response(text) == '{"result": 42}'

    def test_corrupts_plain_text_ending_with_json(self):
        """Without guard, plain text ending with JSON-like braces gets corrupted.

        This documents why server.py wraps the call with `if response_format`.
        """
        from vllm_mlx.api.utils import extract_json_from_response

        # Plain text that happens to end with balanced braces
        plain = 'The config looks like {"debug": true}'
        result = extract_json_from_response(plain)
        # The function extracts '{"debug": true}' — losing the prefix
        assert result == '{"debug": true}'
        assert result != plain

    def test_returns_original_when_no_json(self):
        """Returns original text when no JSON structure found."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = "Hello, world!"
        assert extract_json_from_response(text) == text


# ---------------------------------------------------------------------------
# configure_logging — quiet chatty third-party loggers
# ---------------------------------------------------------------------------


class TestConfigureLogging:
    """Verify chatty transport-layer loggers are silenced at INFO/WARNING but
    not at DEBUG, so HF Hub / httpx noise doesn't drown out startup."""

    @pytest.fixture(autouse=True)
    def _reset_loggers(self):
        import logging as _logging

        names = ("httpx", "httpcore", "urllib3", "huggingface_hub")
        saved = {n: _logging.getLogger(n).level for n in names}
        yield
        for n, lvl in saved.items():
            _logging.getLogger(n).setLevel(lvl)

    def test_info_silences_chatty_loggers(self):
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("INFO")
        for name in ("httpx", "httpcore", "urllib3", "huggingface_hub"):
            assert _logging.getLogger(name).level == _logging.WARNING

    def test_debug_lets_chatty_loggers_through(self):
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("DEBUG")
        for name in ("httpx", "httpcore", "urllib3", "huggingface_hub"):
            assert _logging.getLogger(name).level == _logging.NOTSET

    def test_idempotent_across_level_toggles(self):
        """INFO → DEBUG → INFO must reset chatty loggers each time."""
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("INFO")
        assert _logging.getLogger("httpx").level == _logging.WARNING
        server.configure_logging("DEBUG")
        assert _logging.getLogger("httpx").level == _logging.NOTSET
        server.configure_logging("INFO")
        assert _logging.getLogger("httpx").level == _logging.WARNING


# ---------------------------------------------------------------------------
# GenerationOutput field-ordering positional-compat regression
# ---------------------------------------------------------------------------


class TestGenerationOutputFieldOrder:
    """Pin the dataclass field order so the engine's public-surface
    positional-construction contract stays stable.

    Codex round-1 review of v0.6.66 (PR #443) caught ``raw_text`` and
    ``reasoning_text`` inserted at positions 2 and 3 of the dataclass,
    silently rebinding ``GenerationOutput("text", [1, 2])`` so that
    ``[1, 2]`` landed in ``raw_text`` (which expects ``str``) and
    ``tokens`` defaulted to ``[]``. The fix moves both new fields to
    the END of the dataclass after ``channel``. These tests pin that
    the contract stays as: positions 0..9 are the v0.6.65 surface
    (``text, tokens, prompt_tokens, completion_tokens, finish_reason,
    new_text, finished, logprobs, channel``), and anything added after
    that must be appended, never inserted.
    """

    def test_positional_text_tokens_binding(self):
        """The minimal positional form — ``(text, tokens)`` — must bind
        as it always did: text → ``.text``, list[int] → ``.tokens``.
        """
        out = GenerationOutput("hello", [1, 2, 3])
        assert out.text == "hello"
        assert out.tokens == [1, 2, 3]
        # All optional fields take their defaults.
        assert out.raw_text == ""
        assert out.reasoning_text == ""
        assert out.prompt_tokens == 0
        assert out.completion_tokens == 0

    def test_positional_full_v065_surface(self):
        """Full positional construction of the v0.6.65 surface must
        still bind to the right fields. Caller order:
        text, tokens, prompt_tokens, completion_tokens, finish_reason,
        new_text, finished, logprobs, channel.
        """
        out = GenerationOutput(
            "T",
            [9, 8],
            10,
            20,
            "stop",
            "delta",
            True,
            None,
            "content",
        )
        assert out.text == "T"
        assert out.tokens == [9, 8]
        assert out.prompt_tokens == 10
        assert out.completion_tokens == 20
        assert out.finish_reason == "stop"
        assert out.new_text == "delta"
        assert out.finished is True
        assert out.logprobs is None
        assert out.channel == "content"
        # New fields default to empty when not passed.
        assert out.raw_text == ""
        assert out.reasoning_text == ""

    def test_field_order_appends_new_fields_at_end(self):
        """Make the rule machine-checkable: new fields added after
        v0.6.65 (``raw_text``, ``reasoning_text``, ``tool_calls``,
        ``cached_tokens``) must be APPENDED in chronological order at
        the end of the dataclass. If a refactor ever reorders them
        back into the middle, this test fails loud instead of producing
        silent positional-bind regressions for downstream callers that
        still construct ``GenerationOutput`` positionally.
        """
        from dataclasses import fields

        names = [f.name for f in fields(GenerationOutput)]
        # The original v0.6.65-and-earlier surface ends at ``channel``.
        # ``raw_text``, ``reasoning_text``, ``tool_calls``, and
        # ``cached_tokens`` were appended in order and must stay in
        # their append positions.
        legacy_tail_idx = names.index("channel")
        appended = names[legacy_tail_idx + 1 :]
        assert appended == [
            "raw_text",
            "reasoning_text",
            "tool_calls",
            "cached_tokens",
        ], (
            f"new GenerationOutput fields must be APPENDED in order "
            f"(raw_text → reasoning_text → tool_calls → cached_tokens) "
            f"to preserve positional-arg compatibility for the "
            f"pre-v0.6.65 surface. Current trailing fields after "
            f"``channel``: {appended}"
        )


# ---------------------------------------------------------------------------
# prefix-cache hit reporting (prompt_tokens_details.cached_tokens)
# ---------------------------------------------------------------------------


class TestGetUsageCachedTokens:
    """Pin the OpenAI ``prompt_tokens_details.cached_tokens`` surface
    for ``get_usage``. Clients that read prefix-cache hits off the usage
    block (OpenAI's cookbook recipe, OpenRouter pass-through, downstream
    cost trackers) rely on this field being populated when the engine
    served any prompt tokens from cache, and absent when it didn't.
    """

    def test_cached_tokens_populated_when_nonzero(self):
        from vllm_mlx.service.helpers import get_usage

        output = GenerationOutput(
            text="hi",
            prompt_tokens=200,
            completion_tokens=50,
            cached_tokens=128,
        )
        usage = get_usage(output)
        assert usage.prompt_tokens == 200
        assert usage.completion_tokens == 50
        assert usage.prompt_tokens_details is not None
        assert usage.prompt_tokens_details.cached_tokens == 128

    def test_prompt_tokens_details_absent_when_no_cache_hit(self):
        """Distinguish "no hit" (field omitted) from "0 reported"
        (field present, value 0). Matches what OpenAI emits when the
        request is below the 1024-token cache threshold — the
        ``prompt_tokens_details`` object simply isn't included.
        """
        from vllm_mlx.service.helpers import get_usage

        output = GenerationOutput(
            text="hi", prompt_tokens=200, completion_tokens=50, cached_tokens=0
        )
        usage = get_usage(output)
        assert usage.prompt_tokens_details is None

    def test_default_generation_output_has_no_prompt_details(self):
        from vllm_mlx.service.helpers import get_usage

        usage = get_usage(GenerationOutput(text=""))
        assert usage.prompt_tokens_details is None


class TestBuildUsageCachedTokens:
    """Pin the OpenAI ``prompt_tokens_details.cached_tokens`` surface
    for ``_build_usage``. Mirrors ``TestGetUsageCachedTokens`` plus the
    reasoning-breakdown branch — the cache field is orthogonal to the
    reasoning split and must coexist with it.
    """

    def test_cached_tokens_alongside_reasoning_breakdown(self, monkeypatch):
        from vllm_mlx.config import get_config
        from vllm_mlx.service.helpers import _build_usage

        cfg = get_config()
        monkeypatch.setattr(cfg, "reasoning_parser_name", "harmony", raising=False)

        output = GenerationOutput(
            text="answer",
            prompt_tokens=400,
            completion_tokens=120,
            cached_tokens=256,
        )
        usage = _build_usage(output, "thought" * 20)

        assert usage.completion_tokens_details is not None
        assert usage.completion_tokens_details.reasoning_tokens > 0
        assert usage.prompt_tokens_details is not None
        assert usage.prompt_tokens_details.cached_tokens == 256

    def test_cached_tokens_in_no_reasoning_branch(self, monkeypatch):
        from vllm_mlx.config import get_config
        from vllm_mlx.service.helpers import _build_usage

        cfg = get_config()
        monkeypatch.setattr(cfg, "reasoning_parser_name", None, raising=False)

        output = GenerationOutput(
            text="answer",
            prompt_tokens=400,
            completion_tokens=120,
            cached_tokens=256,
        )
        usage = _build_usage(output, None)

        assert usage.completion_tokens_details is None
        assert usage.prompt_tokens_details is not None
        assert usage.prompt_tokens_details.cached_tokens == 256

    def test_no_cache_hit_leaves_details_absent_with_reasoning(self, monkeypatch):
        from vllm_mlx.config import get_config
        from vllm_mlx.service.helpers import _build_usage

        cfg = get_config()
        monkeypatch.setattr(cfg, "reasoning_parser_name", "harmony", raising=False)

        output = GenerationOutput(
            text="answer",
            prompt_tokens=50,
            completion_tokens=10,
            cached_tokens=0,
        )
        usage = _build_usage(output, "thinking")
        assert usage.prompt_tokens_details is None
        assert usage.completion_tokens_details is not None

    def test_synthetic_streaming_namespace_without_field(self, monkeypatch):
        """The chat streaming path builds a ``_UsageOutput`` namespace
        in ``routes/chat.py`` and calls ``_build_usage`` with it. Pre-
        patch namespaces (or third-party engine wrappers) may not carry
        ``cached_tokens`` — the builder must fall back gracefully to
        "no cache hit reported" instead of raising AttributeError.
        """
        from vllm_mlx.config import get_config
        from vllm_mlx.service.helpers import _build_usage

        cfg = get_config()
        monkeypatch.setattr(cfg, "reasoning_parser_name", None, raising=False)

        class _UsageOutput:
            pass

        u = _UsageOutput()
        u.prompt_tokens = 100
        u.completion_tokens = 50
        u.text = "answer"
        # NOTE: no ``cached_tokens`` attribute set.

        usage = _build_usage(u, None)
        assert usage.prompt_tokens == 100
        assert usage.completion_tokens == 50
        assert usage.prompt_tokens_details is None
